name: project_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  # Flutter dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Vader dependencies:
  vader_app: 0.3.2
  vader_core: 0.4.2

  # Design dependencies:
  cupertino_icons: 1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: 6.9.5
  go_router_builder: 2.9.0
  flutter_lints: 6.0.0
  build_runner: 2.5.4
  bloc_test: 10.0.0
  freezed: 2.5.8
  test: 1.26.2

flutter:
  uses-material-design: true

  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
