version: '3'
# Manual is here: https://taskfile.dev/usage/

tasks:
  help:
    aliases: [default]
    cmd: "task --list"

  update-dependencies:
    desc: "Updates Dart dependencies"
    cmd: "fvm dart pub get"

  build-runner-watch:
    cmd: "fvm dart run build_runner watch --delete-conflicting-outputs"
    desc: "Runs code generation with watch (build_runner)"

  build-runner:
    cmd: "fvm dart run build_runner build --delete-conflicting-outputs"
    desc: "Runs code generation (build_runner)"

  release-android-bundle:
    cmd: "fvm flutter build appbundle --release -t lib/app.dart"
    desc: "Create release android app bundle"

  release-android-apk:
    cmd: "fvm flutter build apk --release -t lib/app.dart"
    desc: "Create release android apk package"

  release-ios-ipa:
    cmd: "fvm flutter build ipa --release -t lib/app.dart"
    desc: "Create release ios ipa package"

  release-ios-app:
    cmd: "fvm flutter build ios --release -t lib/app.dart"
    desc: "Create release ios app package"

  get-android-certificate-fingerprint:
    cmd: "bash bin/get-sha.sh"
    desc: "Get SHA256 certificate fingerprint for Android package"

  run-app:
    cmd: "fvm flutter run -t lib/app.dart"
    desc: "Run application"

  run-tests:
    cmd: "fvm flutter test"
    desc: "Run tests"

  create-code:
    cmd: "./bin/code_builder -d lib/features/"
    desc: "Create code from mason template"

  generate-launcher-icons:
    cmd: "fvm dart run flutter_launcher_icons"
    desc: "Generate launcher icons"

  generate-package-name:
    cmd: "fvm dart run package_rename"
    desc: "Generate package name"

  generate-localizations:
    cmd: "fvm flutter gen-l10n"
    desc: "Generate Flutter localizations"

